spring:
  profiles:
    active: dev
  application:
    name: rra_vms
  datasource:
    url: jdbc:postgresql://localhost:5432/${DATABASE_NAME}
    password: ${DATABASE_PASSWORD}
    username: ${DATABASE_USER}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
#    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    driver-class-name: org.postgresql.Driver
    password: ${DATABASE_PASSWORD}
    user: ${DATABASE_USER}
    url: jdbc:postgresql://localhost:5432/${DATABASE_NAME}


  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

server:
  port: 8000

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui




jwt:
  secretKey: ${JWT_SECRET_KEY}

